export const IMAGES = [
  '/carousel1.jpg',
  '/carousel2.webp',
  'carousel3.webp',
  'carousel4.jpg',
];

export const JOURNALS_INDEX = [
  {
    id: 1,
    name: {
      img: '/carousel1.jpg',
      title: 'acosutic',
    },
    issn: '2624-599X',
    launchDate: 2020,
    if: '-',
    citeScore: '4.0',
    currentIssue: 'v.5(2),Jun 2023',
    totalArticles: '245',
  },
  {
    id: 2,
    name: {
      img: '/carousel2.webp',
      title: 'BioTech Advances',
    },
    issn: '1234-5678',
    launchDate: 2019,
    if: '1.2',
    citeScore: '3.5',
    currentIssue: 'v.6(1),Mar 2024',
    totalArticles: '198',
  },
  {
    id: 3,
    name: {
      img: 'carousel4.jpg',
      title: 'Innovative Engineering',
    },
    issn: '2345-6789',
    launchDate: 2021,
    if: '2.3',
    citeScore: '4.1',
    currentIssue: 'v.2(3),Sep 2023',
    totalArticles: '112',
  },
  {
    id: 4,
    name: {
      img: 'carousel4.jpg',
      title: 'Medical Insights',
    },
    issn: '3456-7890',
    launchDate: 2020,
    if: '3.5',
    citeScore: '5.0',
    currentIssue: 'v.8(2),Jul 2023',
    totalArticles: '312',
  },
  {
    id: 5,
    name: {
      img: 'carousel3.webp',
      title: 'Quantum Computing',
    },
    issn: '4567-8901',
    launchDate: 2022,
    if: '-',
    citeScore: '2.8',
    currentIssue: 'v.1(4),Aug 2024',
    totalArticles: '85',
  },
  {
    id: 6,
    name: {
      img: 'carousel1.jpg',
      title: 'Data Science Journal',
    },
    issn: '5678-9012',
    launchDate: 2018,
    if: '4.2',
    citeScore: '4.7',
    currentIssue: 'v.7(3),Dec 2023',
    totalArticles: '270',
  },
  {
    id: 7,
    name: {
      img: 'carousel1.jpg',
      title: 'AI & Robotics',
    },
    issn: '6789-0123',
    launchDate: 2021,
    if: '3.0',
    citeScore: '3.9',
    currentIssue: 'v.4(2),Jun 2024',
    totalArticles: '150',
  },
  {
    id: 8,
    name: {
      img: 'carousel4.jpg',
      title: 'Environmental Studies',
    },
    issn: '7890-1234',
    launchDate: 2019,
    if: '2.7',
    citeScore: '3.6',
    currentIssue: 'v.9(1),Mar 2024',
    totalArticles: '220',
  },
  {
    id: 9,
    name: {
      img: 'carousel3.webp',
      title: 'Cybersecurity Trends',
    },
    issn: '8901-2345',
    launchDate: 2022,
    if: '4.5',
    citeScore: '4.2',
    currentIssue: 'v.3(2),Jul 2024',
    totalArticles: '190',
  },
  {
    id: 10,
    name: {
      img: 'carousel1.jpg',
      title: 'Economics Today',
    },
    issn: '9012-3456',
    launchDate: 2018,
    if: '3.8',
    citeScore: '4.3',
    currentIssue: 'v.6(4),Nov 2023',
    totalArticles: '250',
  },
  {
    id: 11,
    name: {
      img: 'carousel1.jpg',
      title: 'Genomics Research',
    },
    issn: '0123-4567',
    launchDate: 2020,
    if: '5.0',
    citeScore: '5.1',
    currentIssue: 'v.5(3),Apr 2024',
    totalArticles: '280',
  },
  {
    id: 12,
    name: {
      img: 'carousel4.jpg',
      title: 'Digital Humanities',
    },
    issn: '1234-5679',
    launchDate: 2021,
    if: '2.6',
    citeScore: '3.3',
    currentIssue: 'v.2(4),Oct 2023',
    totalArticles: '135',
  },
];

export const MDPI_TOPICS = [
  {
    title:
      'Ethical, Legal and Forensic Issues regarding Vulnerable Populations',
    editors: ['Stavroula Papadodima', 'Flora Bacopoulou'],
    submissionDeadline: '19 Sep 2024',
    articlesCount: 7,
    views: 9026,
    submissionStatus: 'Open',
    participatingJournals: [
      'Forensic Sciences',
      'Healthcare',
      'Journal of Clinical Medicine',
      'Journal of Personalized Medicine',
    ],
  },
  {
    title: 'Advances in Pediatric Healthcare and Medicine',
    editors: ['John Doe', 'Jane Smith'],
    submissionDeadline: '15 Dec 2024',
    articlesCount: 12,
    views: 5678,
    submissionStatus: 'Open',
    participatingJournals: [
      'Journal of Pediatrics',
      'Healthcare',
      'Clinical Pediatrics',
      'Journal of Medical Research',
    ],
  },
  {
    title: 'Innovations in AI for Healthcare Systems',
    editors: ['Michael Brown', 'Laura Johnson'],
    submissionDeadline: '10 Nov 2024',
    articlesCount: 10,
    views: 12034,
    submissionStatus: 'Closed',
    participatingJournals: [
      'Journal of AI Research',
      'Healthcare Innovation',
      'Journal of Medical Informatics',
      'AI in Medicine',
    ],
  },
  {
    title: 'Global Challenges in Infectious Disease Control',
    editors: ['Sophia Lee', 'David Chen'],
    submissionDeadline: '30 Sep 2024',
    articlesCount: 9,
    views: 8045,
    submissionStatus: 'Open',
    participatingJournals: [
      'Infectious Diseases Journal',
      'Journal of Clinical Medicine',
      'Healthcare',
      'Global Health Perspectives',
    ],
  },
  {
    title: 'Sustainability in Healthcare Practices',
    editors: ['Emily Green', 'Olivia White'],
    submissionDeadline: '25 Jan 2025',
    articlesCount: 15,
    views: 15432,
    submissionStatus: 'Open',
    participatingJournals: [
      'Journal of Sustainability',
      'Healthcare',
      'Environmental Health',
      'Sustainable Medicine',
    ],
  },
  {
    title: 'Mental Health and Well-Being in the Digital Age',
    editors: ['Kevin Adams', 'Rachel Carter'],
    submissionDeadline: '05 Oct 2024',
    articlesCount: 8,
    views: 6903,
    submissionStatus: 'Closed',
    participatingJournals: [
      'Journal of Mental Health',
      'Healthcare',
      'Digital Health',
      'Psychiatry Today',
    ],
  },
];

export const REVIEWERS_GUIDE = [
  { id: 1, title: 'Peer Review and Editorial Procedure', section: 'section1' },
  {
    id: 2,
    title: 'Reviewers’ Profile and Responsibilities',
    section: 'section2',
  },
  { id: 3, title: 'Reviewers’ Benefits', section: 'section3' },
  { id: 4, title: 'Reviewer Board', section: 'section4' },
  { id: 5, title: 'Volunteer Reviewers', section: 'section5' },
  {
    id: 6,
    title: 'General Guideline for MDPI Reviewers Recruiting Program',
    section: 'section6',
  },
  { id: 7, title: 'General Guidelines for Reviewers', section: 'section7' },
  { id: 7.1, title: 'Invitation to Review', section: 'section7.1' },
  { id: 7.2, title: 'Potential Conflicts of Interest', section: 'section7.2' },
  { id: 7.3, title: 'Declaration of Confidentiality', section: 'section7.3' },
  { id: 7.4, title: 'Review Reports', section: 'section7.4' },
  { id: 7.5, title: 'Rating the Manuscript', section: 'section7.5' },
  { id: 7.6, title: 'Overall Recommendation', section: 'section7.6' },
  {
    id: 7.7,
    title: 'Guidelines for Reviewers for Registered Reports Papers',
    section: 'section7.7',
  },
  {
    id: 7.8,
    title:
      'Guidelines for Reviewers for Depositing Review Activities into ORCID',
    section: 'section7.8',
  },
];

export const CONTENT = [
  { id: 1, title: 'MDPI Statement', section: 'section1' },
  { id: 2, title: 'Publication Ethics Statement', section: 'section2' },
  { id: 3, title: 'Ethical Guidelines for Authors', section: 'section3' },
  { id: 4, title: 'Authorship', section: 'section4' },
  {
    id: 5,
    title: 'Plagiarism, Data Fabrication and Image Manipulation',
    section: 'section5',
  },
  { id: 6, title: 'Research Involving Human Subjects', section: 'section6' },
  {
    id: 7,
    title: 'Research Involving the Use of Animals in Research',
    section: 'section7',
  },
  { id: 8, title: 'Research Involving Cell Lines', section: 'section8' },
  { id: 9, title: 'Research Involving Plants', section: 'section9' },
  { id: 10, title: 'Clinical Trials Registration', section: 'section10' },
  { id: 11, title: 'Dual Use Research of Concern', section: 'section11' },
  { id: 12, title: 'Sex and Gender in Research', section: 'section12' },
  { id: 13, title: 'Borders and Territories', section: 'section13' },
  { id: 14, title: 'Potential Conflicts of Interest', section: 'section14' },
  {
    id: 15,
    title: 'Intellectual Property i.a. Copyright, Patent and Licensing',
    section: 'section15',
  },
  { id: 16, title: 'Citation Policies', section: 'section16' },
  { id: 17, title: 'MDPI Research Data Policies', section: 'section17' },
  {
    id: 18,
    title: 'Ethical Guidelines for Reviewers and Editors',
    section: 'section18',
  },
  { id: 19, title: 'Comments and Complaints', section: 'section19' },
  { id: 20, title: 'Updating Published Papers', section: 'section20' },
  { id: 21, title: 'Contact', section: 'section21' },
];

export const ARTICLES = [
  {
    id: 1,
    title: 'General Information on MDPI’s Article Processing Charges (APC)',
    section: 'section1',
  },
  { id: 2, title: 'Journal Specific APCs', section: 'section2' },
  { id: 3, title: 'Market-Specific Taxes', section: 'section3' },
  { id: 4, title: 'Extensive English Editing', section: 'section4' },
  { id: 5, title: 'Funding of APCs and BPCs', section: 'section5' },
  { id: 6, title: 'Discounts on APCs', section: 'section6' },
  { id: 7, title: 'Accepted Currencies', section: 'section7' },
  { id: 8, title: 'Accepted Methods of Payment', section: 'section8' },
  { id: 9, title: 'MDPI Invoicing FAQ', section: 'section9' },
];

export const OFFICES = [
  {
    room: 'Basel room',
    addressLine1: 'MDPI AG, Grosspeteranlage 5',
    addressLine2: '4052 Basel, Switzerland',
    phone: '+41 61 683 77 34',
    officeHours: '9:00-17:00 (GMT +1)',
    publicHolidays: 'Public Holidays',
    history: 'Learn more about the history of the headquarter building.',
  },
  {
    room: 'Zurich room',
    addressLine1: 'MDPI AG, Bahnhofstrasse 10',
    addressLine2: '8001 Zurich, Switzerland',
    phone: '+41 44 123 45 67',
    officeHours: '9:00-18:00 (GMT +1)',
    publicHolidays: 'Public Holidays',
    history: 'Discover the heritage of the Zurich office.',
  },
  {
    room: 'New York office',
    addressLine1: 'MDPI AG, 123 Park Avenue',
    addressLine2: 'New York, USA',
    phone: '+1 212 555 6789',
    officeHours: '9:00-17:00 (EST)',
    publicHolidays: 'US National Holidays',
    history: 'Learn about the New York office establishment.',
  },
  {
    room: 'London office',
    addressLine1: 'MDPI AG, 50 Oxford Street',
    addressLine2: 'London, UK',
    phone: '+44 20 7946 0958',
    officeHours: '9:00-17:00 (GMT)',
    publicHolidays: 'UK Bank Holidays',
    history: 'Read about the history of our London location.',
  },
  {
    room: 'Tokyo office',
    addressLine1: 'MDPI AG, Shibuya-ku',
    addressLine2: 'Tokyo, Japan',
    phone: '+81 3 1234 5678',
    officeHours: '9:00-18:00 (JST)',
    publicHolidays: 'Japanese National Holidays',
    history: 'Find out more about the Tokyo office’s foundation.',
  },
  {
    room: 'Sydney office',
    addressLine1: 'MDPI AG, George Street',
    addressLine2: 'Sydney, Australia',
    phone: '+61 2 9876 5432',
    officeHours: '9:00-17:00 (AEST)',
    publicHolidays: 'Australian Public Holidays',
    history: 'Learn the history of the Sydney office.',
  },
];
